import { Student } from './Student';
export const STUDENTS: Student[] = [
  {
    fname: 'John',
    lname: 'Doe',
    dorm: 'BARH',
    room: 'C101',
    status: 'None',
    rin: 660000001,
    email: 'doej4@rpi.edu',
    numemail: 0,
    ewsreason: 'Failing the course',
    ewsdate: 'Sept 1',
    course: 'DATA STRUCTURES',
    coursesubject: 'CSCI',
    coursecode: '1200',
    profname: 'Barb C.',
    profcomment: 'John got submittied',
    lacomment: undefined,
    laassigned: undefined,
  },
  {
    fname: 'Adam',
    lname: 'Smith',
    dorm: 'BARH',
    room: 'C201',
    status: 'None',
    rin: 660000002,
    email: 'smitha2@rpi.edu',
    numemail: 1,
    ewsreason: 'Missing/Poor Assignments',
    ewsdate: 'Sept 1',
    course: 'INTRO TO BIOLOGY LAB',
    coursesubject: 'BIOL',
    coursecode: '1100',
    profname: undefined,
    profcomment: undefined,
    lacomment: undefined,
    laassigned: 'Huy',
  },
];
