import { Student } from './Student';
export const STUDENTS: Student[] = [
  {
    fname: 'John',
    lname: 'Doe',
    dorm: 'BARH',
    room: 'C101',
    status: 'None',
    rin: 660000001,
    email: 'doej4@rpi.edu',
    numemail: 0,
    numews: 1,
    ewsreason: 'Failing the course',
    ewsdate: 'Sept 1',
    course: 'DATA STRUCTURES',
    coursesubject: 'CSCI',
    coursecode: '1200',
    profname: 'Barb C.',
    profcomment: 'John got submittied',
    lacomment: undefined,
    assignedla: 'None',
  },
  {
    fname: 'Adam',
    lname: 'Smith',
    dorm: 'BARH',
    room: 'C201',
    status: 'Emailed once',
    rin: 660000002,
    email: 'smitha2@rpi.edu',
    numemail: 1,
    numews: 2,
    ewsreason: 'Missing/Poor Assignments',
    ewsdate: 'Sept 1',
    course: 'INTRO TO BIOLOGY LAB',
    coursesubject: 'BIOL',
    coursecode: '1100',
    profname: undefined,
    profcomment: undefined,
    lacomment: undefined,
    assignedla: 'Huy',
  },
  {
    fname: 'Isabella',
    lname: 'Baker',
    dorm: 'BARH',
    room: 'D211',
    status: 'Scheduled Meeting',
    rin: 660000003,
    email: 'bakeri@rpi.edu',
    numemail: 2,
    numews: 3,
    ewsreason: 'Missing/Poor Assignments',
    ewsdate: 'Sept 2',
    course: 'CALCULUS I',
    coursesubject: 'MATH',
    coursecode: '1100',
    profname: undefined,
    profcomment: undefined,
    lacomment: undefined,
    assignedla: 'Madeline',
  },
  {
    fname: 'Isabella',
    lname: 'Baker',
    dorm: 'BARH',
    room: 'D211',
    status: 'Scheduled Meeting',
    rin: 660000003,
    email: 'bakeri@rpi.edu',
    numemail: 2,
    numews: 3,
    ewsreason: 'Missing/Poor Assignments',
    ewsdate: 'Sept 2',
    course: 'CALCULUS I',
    coursesubject: 'MATH',
    coursecode: '1100',
    profname: undefined,
    profcomment: undefined,
    lacomment: undefined,
    assignedla: 'Madeline',
  },
  {
    fname: 'Adam',
    lname: 'Smith',
    dorm: 'BARH',
    room: 'C201',
    status: 'Emailed once',
    rin: 660000002,
    email: 'smitha2@rpi.edu',
    numemail: 1,
    numews: 2,
    ewsreason: 'Poor Attendance',
    ewsdate: 'Sept 1',
    course: 'INTRO TO BIOLOGY',
    coursesubject: 'BIOL',
    coursecode: '1100',
    profname: undefined,
    profcomment: undefined,
    lacomment: undefined,
    assignedla: 'Huy',
  },
  {
    fname: 'Isabella',
    lname: 'Baker',
    dorm: 'BARH',
    room: 'D211',
    status: 'Scheduled Meeting',
    rin: 660000003,
    email: 'bakeri@rpi.edu',
    numemail: 2,
    numews: 3,
    ewsreason: 'Missing/Poor Assignments',
    ewsdate: 'Sept 2',
    course: 'CALCULUS I',
    coursesubject: 'MATH',
    coursecode: '1100',
    profname: undefined,
    profcomment: undefined,
    lacomment: undefined,
    assignedla: 'Madeline',
  },
];
