import { Student } from './interfaces/student';
export const STUDENTS: Student[] = [
  {
    fname: 'John',
    lname: 'Doe',
    dorm: 'BARH',
    room: 'C101',
    status: 'None',
    rin: 660000001,
    email: 'doej4@rpi.edu',
    emailcount: 0,
    ewscount: 1,
    ewsreason: 'Failing the cname',
    ewsdate: 'Sept 1',
    cname: 'DATA STRUCTURES',
    csubject: 'CSCI',
    ccode: '1200',
    cprof: 'Barb C.',
    profcomment: 'John got submittied',
    lacomment: undefined,
    assignedla: undefined,
  },
  {
    fname: 'Adam',
    lname: 'Smith',
    dorm: 'BARH',
    room: 'C201',
    status: 'Emailed once',
    rin: 660000002,
    email: 'smitha2@rpi.edu',
    emailcount: 1,
    ewscount: 2,
    ewsreason: 'Missing/Poor Assignments',
    ewsdate: 'Sept 1',
    cname: 'INTRO TO BIOLOGY LAB',
    csubject: 'BIOL',
    ccode: '1100',
    cprof: undefined,
    profcomment: undefined,
    lacomment: undefined,
    assignedla: 'Huy',
  },
  {
    fname: 'Isabella',
    lname: 'Baker',
    dorm: 'BARH',
    room: 'D211',
    status: 'Scheduled Meeting',
    rin: 660000003,
    email: 'bakeri@rpi.edu',
    emailcount: 2,
    ewscount: 3,
    ewsreason: 'Missing/Poor Assignments',
    ewsdate: 'Sept 2',
    cname: 'CALCULUS I',
    csubject: 'MATH',
    ccode: '1100',
    cprof: undefined,
    profcomment: undefined,
    lacomment: undefined,
    assignedla: 'Madeline',
  },
  {
    fname: 'Isabella',
    lname: 'Baker',
    dorm: 'BARH',
    room: 'D211',
    status: 'Scheduled Meeting',
    rin: 660000003,
    email: 'bakeri@rpi.edu',
    emailcount: 2,
    ewscount: 3,
    ewsreason: 'Missing/Poor Assignments',
    ewsdate: 'Sept 2',
    cname: 'CALCULUS I',
    csubject: 'MATH',
    ccode: '1100',
    cprof: undefined,
    profcomment: undefined,
    lacomment: undefined,
    assignedla: 'Madeline',
  },
  {
    fname: 'Adam',
    lname: 'Smith',
    dorm: 'BARH',
    room: 'C201',
    status: 'Emailed once',
    rin: 660000002,
    email: 'smitha2@rpi.edu',
    emailcount: 1,
    ewscount: 2,
    ewsreason: 'Poor Attendance',
    ewsdate: 'Sept 1',
    cname: 'INTRO TO BIOLOGY',
    csubject: 'BIOL',
    ccode: '1100',
    cprof: undefined,
    profcomment: undefined,
    lacomment: undefined,
    assignedla: 'Huy',
  },
  {
    fname: 'Isabella',
    lname: 'Baker',
    dorm: 'BARH',
    room: 'D211',
    status: 'Scheduled Meeting',
    rin: 660000003,
    email: 'bakeri@rpi.edu',
    emailcount: 2,
    ewscount: 3,
    ewsreason: 'Missing/Poor Assignments',
    ewsdate: 'Sept 2',
    cname: 'CALCULUS I',
    csubject: 'MATH',
    ccode: '1100',
    cprof: undefined,
    profcomment: undefined,
    lacomment: undefined,
    assignedla: 'Madeline',
  },
];
